### ISSUE TITLE
Viterbi algorithm never defined

### ISSUE THREAD

**Issue by brennancheung** [udacity/nlpnd-waffle-issues#2]
In Section 1, Lesson 4, Luis says the Viterbi algorithm will be given in the next video, then in the next video Luis says the Viterbi algorithm will be given in the next video?!?!...  Then nothing.  The end.  :(

**Comment by cgearhart** [comment]
I'll assign luis to check the videos.

**Comment by cgearhart** [comment]
Sorry about that. Luis had missed that video in the classroom. It should be there now.
