### ISSUE TITLE
pydotplus dependency not installed in Jupyter 3 kernel environment

### ISSUE THREAD

**Issue by caitriggs** [udacity/nlpnd-waffle-issues#3]
Line 6 of HMM warmup (optional).ipynb yields an ImportModule Error for pydotplus.

Had to `pip install graphviz` and `pip install pydotplus` to run `show_model(model, figsize=(5, 5), filename="example.png", overwrite=True, show_ends=False)`

Added `%matplotlib inline` after matplotlib.pyplot import as well to display plot as cell output

**Comment by caitriggs** [comment]
* `brew install graphviz` on mac OSX

**Comment by cgearhart** [comment]
Internal ticket #675 filed with workspaces team. I'll update the instructions to clarify that graphviz is required to visualize the network.

Thank you for reporting!

**Comment by caitriggs** [comment]
To install the dependencies in the Workspace using a Jupyter terminal, the following worked for me:
`sudo apt update` ->`sudo apt install graphviz` -> `pip install pydotplus`
