### ISSUE TITLE
Will the subtitles be provided for the video in the future?

### ISSUE THREAD

**Issue by fantasycheng** [udacity/nlpnd-waffle-issues#4]
I am a Chinese student. It is difficult for me to watch the course video without subtitles. So I want to know whether the subtitles will be provided in the future.

**Comment by cgearhart** [comment]
I just kicked off the job to generate subtitles and zip files of the lecture videos. Please check in the classroom a bit later and let me know if you don't see them.

**Comment by fantasycheng** [comment]
I just checked all videos in Lesson 4 and 5, and found only Lesson 4 Video 1, 11, 12 have subtitles from China. If I try to visit the website from USA IP address and watch these video on Youtube, some videos have subtitles generated by Youtube.
