### ISSUE TITLE
link is incorrect in week 2 prereqs

### ISSUE THREAD

**Issue by benjaminaschultz** [udacity/nlpnd-waffle-issues#5]
The link that should go to chapter 10 in the book on pos tagging goes to chapter 9 instead.

**Comment by benjaminaschultz** [comment]
![DeepinScreenshot_select-area_20180413085258.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad0a78c699cb50015abd7fc/125516c66e82c728ace21e0d46cc919f338b8d9a8cfbba46aa4ef89b3d7934762501a03f3d84f12dbe7d29515e574ea8405b5f4cf9fb8c23b4aa2e30c80351b882294d7ed43840fdbed71abe03b925884680bfbc8a4d93ea3c27ef8d865d220c4749d7ab0268f9d31e8a4afc59e34e5fa5163460e07435754f921c7225792a.png)

**Comment by cgearhart** [comment]
Fixed! Thanks for reporting.
